name: Router Maestro E2E

on:
  pull_request:
    branches: [main, cicd]
  workflow_dispatch:
  push:
    branches: [main, cicd]

jobs:
  expo-go-dev-maestro-router:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: ðŸ” Find Yarn Cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: â™»ï¸ Restore Yarn Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-

      - name: Install dependencies
        run: YARN_IGNORE_SCRIPTS=true yarn --frozen-lockfile

      - name: Install Maestro
        run: |
          export MAESTRO_VERSION=1.39.9
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Start Expo Dev Client
        run: |
          # Start the Expo Dev Client
          npx expo run:ios &
          sleep 10

      - name: Run Maestro tests
        env:
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 360000
        run: |
          # Run the Expo Dev Server in the background
          maestro test maestro/ --format junit --no-ansi --debug-output .logs

      - name: Store tests result
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: e2e_report
          path: report.xml

      - name: Record Maestro tests
        if: ${{ success() }}
        env:
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 360000
        run: |
          for i in maestro/*.yml; do maestro record --local $i artifact/"${i:8:-4}.mp4" --no-ansi --debug-output .logs; done;
          for i in maestro/*.yaml; do maestro record --local $i artifact/"${i:8:-4}.mp4" --no-ansi --debug-output .logs; done;

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-logs
          path: ~/artifact/**/*.mp4

      - name: Log output
        if: ${{ failure() }}
        working-directory: .logs/.maestro/tests
        run: |
          cd $(find . -type d -name "20??-??-*"  | head -n 1)
          cat maestro.log
          exit 1